### DISCUSSION TITLE
PEP 735 Dependency Group support?

### DISCUSSION THREAD

**Discussion by chrisjsewell** [tox-dev/tox-uv#114] [Q&A] [answered]
Heya, both uv and tox have now added support for this:

- https://github.com/tox-dev/tox/pull/3409
- https://github.com/astral-sh/uv/pull/8272

I haven't checked yet, but do you know if this should already now work for tox-uv, or would changes be required?

**Comment by chrisjsewell** [comment]
I note that it is not yet supported for `uv pip`, nor pip itself (https://github.com/pypa/pip/issues/12963), if that makes any difference

**Comment by azmeuk** [comment]
I tested passing groups to `uv_sync_flags` with this configuration (with the new [tox 4.21 native toml configuration support](https://github.com/tox-dev/tox/issues/999)), as suggested in #113, but without success at the moment.

```toml
[tool.tox.env.doc]
runner = "uv-venv-lock-runner"
uv_sync_flags = ["--group=doc"]
commands = [
    ["sphinx-build", "--builder", "html", "doc", "build/sphinx/html"],
    ["sphinx-build", "--builder", "man", "doc", "build/sphinx/html"],
]
```

It fails with `TypeError: '--group=doc' is not list`.
