### DISCUSSION TITLE
Specify `uv_resolution` on command line?

### DISCUSSION THREAD

**Discussion by nschloe** [tox-dev/tox-uv#141] [Q&A]
As part of my CI workflow, I'd like to use tox-uv to test my packages against the highest- and lowest-possible dependencies. I see that 

```toml
[env_run_base]
uv_resolution = "lowest-direct"
```

can be hard-coded in to `tox.toml`. How would I specify `highest` and `lowest` on the command-line though?

(As a side-question: It does factor in all package dependencies, not only test dependencies, right?)
