### DISCUSSION TITLE
Running tox-uv in GitHub Actions runs all environments in every build matrix

### DISCUSSION THREAD

**Discussion by Diapolo10** [tox-dev/tox-uv#149] [Q&A]
I know that title doesn't make much sense, but basically I'm porting a Poetry-based project template to uv and for some reason that caused Tox to switch from using one environment per build matrix to all of them - I suppose this is technically okay, but it also means if one Python version fails it fails the entire OS matrix.

Case in point, please look at these logs: https://github.com/Diapolo10/python-uv-template/pull/1

```txt
py39: freeze> /home/runner/work/_temp/setup-uv-cache/archive-v0/wGwBnBvftscqoUOOZoTcI/bin/uv --color never pip freeze
py39: python-dotenv==1.0.1,python-uv-template @ file:///home/runner/work/python-uv-template/python-uv-template/.tox/.tmp/package/1/python_uv_template-0.0.0.post1.dev0+7163a68.tar.gz,tomli==2.2.1
py39: commands[0]> uv run --frozen pytest
warning: `VIRTUAL_ENV=.tox/py39` does not match the project environment path `.venv` and will be ignored
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0
cachedir: .tox/py39/.pytest_cache
rootdir: /home/runner/work/python-uv-template/python-uv-template
configfile: pyproject.toml
testpaths: tests
plugins: cov-6.0.0, anyio-4.7.0
collected 2 items

tests/test_default.py ..                                                 [100%]

---------- coverage: platform linux, python 3.12.3-final-0 -----------
Coverage HTML written to dir tests/reports/coverage-html
Coverage XML written to file tests/reports/coverage.xml


============================== 2 passed in 0.08s ===============================
py39: commands[1]> uv run --frozen coverage report
warning: `VIRTUAL_ENV=.tox/py39` does not match the project environment path `.venv` and will be ignored
Name                           Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------
src/project_name/__init__.py       0      0      0      0   100%
src/project_name/lib.py            2      0      0      0   100%
----------------------------------------------------------------
TOTAL                              2      0      0      0   100%
py39: OK ✔ in 4.36 seconds
py310: venv> /home/runner/work/_temp/setup-uv-cache/archive-v0/wGwBnBvftscqoUOOZoTcI/bin/uv venv -p cpython3.10 --allow-existing /home/runner/work/python-uv-template/python-uv-template/.tox/py310
py310: install_package_deps> /home/runner/work/_temp/setup-uv-cache/archive-v0/wGwBnBvftscqoUOOZoTcI/bin/uv pip install 'python-dotenv>=1.0.1' 'tomli>=2.2.1; python_version < "3.11"'
py310: install_package> /home/runner/work/_temp/setup-uv-cache/archive-v0/wGwBnBvftscqoUOOZoTcI/bin/uv pip install --reinstall --no-deps python-uv-template@/home/runner/work/python-uv-template/python-uv-template/.tox/.tmp/package/2/python_uv_template-0.0.0.post1.dev0+7163a68.tar.gz
py310: freeze> /home/runner/work/_temp/setup-uv-cache/archive-v0/wGwBnBvftscqoUOOZoTcI/bin/uv --color never pip freeze
py310: python-dotenv==1.0.1,python-uv-template @ file:///home/runner/work/python-uv-template/python-uv-template/.tox/.tmp/package/2/python_uv_template-0.0.0.post1.dev0+7163a68.tar.gz,tomli==2.2.1
py310: commands[0]> uv run --frozen pytest
warning: `VIRTUAL_ENV=.tox/py310` does not match the project environment path `.venv` and will be ignored
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0
```

As you can see, both 3.9 and 3.10 are being used in the same job. But it used to be only one version per job, with me having a job for each version/OS. I'm not really sure what I'm doing wrong - most likely my Tox configuration

```toml
[tool.tox]
legacy_tox_ini = """
[tox]
env_list = py3{9, 10, 11, 12}, pypy3
skip_missing_interpreters = true

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    pypy-3.10: pypy3

[testenv]
pass_env =
    GITHUB_*
    FORCE_COLOR
allowlist_externals = uv

commands =
    uv run --frozen pytest
    uv run --frozen coverage report
"""
```

and build matrix

```yaml
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [
          '3.9',
          '3.10',
          '3.11',
          '3.12',
          'pypy-3.10',
        ]

        exclude:
          - os: windows-latest
            python-version: pypy-3.10
          - os: macos-latest
            python-version: pypy-3.10
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
```

are conflicting somehow.

Any ideas?
