### ISSUE TITLE
`uv_sync_flags` and tox 4.21 native toml configuration

### ISSUE THREAD

**Issue by azmeuk** [tox-dev/tox-uv#116]
I tested passing groups to `uv_sync_flags` with this configuration (with the new [tox 4.21 native toml configuration support](https://github.com/tox-dev/tox/issues/999)), as suggested in #113, but without success at the moment:

```toml
[tool.tox.env.doc]
runner = "uv-venv-lock-runner"
uv_sync_flags = ["--group=doc"]
commands = [
    ["sphinx-build", "--builder", "html", "doc", "build/sphinx/html"],
    ["sphinx-build", "--builder", "man", "doc", "build/sphinx/html"],
]
```

It fails with `TypeError: '--group=doc' is not list`.

When passing a simple string like `uv_sync_flags = "--group=doc"` it also fails with the same error message.

_Originally posted by @azmeuk in https://github.com/tox-dev/tox-uv/discussions/114#discussioncomment-11084270_
