### ISSUE TITLE
the commands attribute is not overwritten by new environments

### ISSUE THREAD

**Issue by eelcovv** [tox-dev/tox-uv#179]
## Issue  

I am using `tox` with `tox-uv` to set up my testing environment. When I run the default `env_run_base`, all tests execute successfully. However, if I add an extra environment based on your examples (using `uv-venv-runner`), the `commands` attribute is not overridden as expected. Instead, the new environment inherits the `commands` from `env_run_base`.  

### Expected Behavior  

I expect the `pytest` tests to run with the following command:  

```shell
tox r -e py311
```  

This works as expected. However, if I run another environment, it also executes `pytest`, even though that is not explicitly set as the command.  

For example, when running:  

```shell
tox r -e fix
```  

I expect `pre-commit run` to be executed (as specified by the command attribute of the fix environment), but instead, `pytest` is inherited from `env_run_base`.  

### Current Behavior  

The `fix` environment is supposed to run:  

```shell
pre-commit run --all-files --show-diff-on-failure
```  

But instead, it executes `pytest tests`, which is inherited from `env_run_base`.  

---

## My Setup  

```toml
[tool.tox]
requires = ["tox>4", "tox-uv>=1.11.3"]
isolated_build = true
# Non-test environments (like 'fix') are not working correctly, as they inherit 'pytest' from env_run_base.
env_list = ["py39", "py310", "py311", "py312", "py313", "dev", "lint"]

# === Base test environment ===
[tool.tox.env_run_base]
description = "Run pytest with coverage under {env_name}"
changedir = "{toxinidir}"
allowlist_externals = ["pytest", "uv"]
dependency_groups = ["test"]
commands = [["pytest"]]

# === Build environment ===
[tool.tox.testenv.build]
description = "Build the package using uv"
changedir = "{toxinidir}"
commands = [["uv build"]]
allowlist_externals = ["uv"]

# === Fix environment (not working as expected) ===
[tool.tox.testenv.fix]
runner = "uv-venv-runner"
description = "Run code formatter and linter (auto-fix)"
skip_install = true
deps = ["pre-commit-uv >= 4.1.1"]
commands = [["pre-commit run --all-files --show-diff-on-failure"]]
```  

---

## Environment  

- **OS**: Windows 11 (PowerShell)  
- **tox-uv Installation**:  

```shell
uv tool install tox --with tox-uv
```  

Installed tools:  

```console
PS> uv tool list
cookiecutter v2.6.0
- cookiecutter.exe
cookiecutter-uv v0.2.0
- ccp.exe
keyring v25.6.0
- keyring.exe
mkdocs v1.6.1
- mkdocs.exe
tox v4.24.1
- tox.exe
twine v6.1.0
- twine.exe
uv-publish v1.2
- uv-p
```  

---

## Output of Running tox  

When I run `tox -rvv`, I see that the `fix` environment still executes `pytest`, instead of `pre-commit`.  

```console
PS> tox r -e fix
...
fix: commands[0]> pytest tests
...
```  

---

## Minimal Example  

To reproduce this issue:  

```console
git clone https://github.com/dave-Lab-and-Engineering/python-build-utils
cd python-build-utils
uv tool install tox --with tox-uv
tox
```  

Even with this setup, the `fix` environment runs `pytest` instead of `pre-commit`, despite the `commands` being explicitly set. Moving everything to `tox.ini` does not resolve the issue.

**Comment by gaborbernat** [comment]
I belive this is what you'd want:
```
git clone https://github.com/dave-Lab-and-Engineering/python-build-utils
cd python-build-utils
uv tool install tox --with tox-uv
tox
```

Why are you running:

```
uv venv
./.venv/Scripts/activate.ps1
uv sync
```

inside there? Seems like you're mixing tox managed and self managed environments 🤔

**Comment by eelcovv** [comment]
you are right, uv sync is not needed. i will change that in my MWE. Nevertheless, the issue remains the same: fix get the command from the test environment, instead of overwriting it with new command given in the fix command:
from the output of running tox (with uv sync)

fix: commands[0]> pytest

**Comment by gaborbernat** [comment]
Your configuration is incorrect, please read the documentation at https://tox.wiki/en/latest/config.html#pyproject-toml-native. Namely `testenv` should be `env`.

**Comment by eelcovv** [comment]
Many thanks for your help! you are right, this indeed now used the correct command. I had based my toml on the example of the tox-uv home where you also use testenv for fix, but perhaps that is for tox.ini? 

I am getting another issue now

I have now changed it to env:

``` toml
[tool.tox.env.fix]
runner = "uv-venv-runner"
description = "run code formatter and linter (auto-fix)"
skip_install = true
dependency_groups = ["dev"]
deps = ["pre-commit-uv >= 4.1.1"]
commands = [["pre-commit run --all-files --show-diff-on-failure"]]
```

Only thing is that iI get this error at the moment:

``` shell
PS> tox r -e fix
fix: commands[0]> "pre-commit run --all-files --show-diff-on-failure"
fix: Exception running subprocess [WinError 2] The system cannot find the file specified
fix: exit 2 (0.00 seconds) C:\Users\eelco\Workspace\Python\Applications\python-build-utils> "pre-commit run --all-files --show-diff-on-failure"
  fix: FAIL code 2 (0.01=setup[0.01]+cmd[0.00] seconds)
  evaluation failed :( (0.08 seconds)
```

U have a dependency_group 'dev' which contains pre-commit, but somehow it is not running. Any idea how to fix that?
