### ISSUE TITLE
uv sync should run with --no-dev

### ISSUE THREAD

**Issue by hynek** [tox-dev/tox-uv#93]
Currently, there's only one flat namespace in `tool.uv.dev-dependencies` that people are likely to use to define their dev environments. When not told otherwise, `uv sync` installs them.

For example

```toml
[project.optional-dependencies]
tests = ["pytest"]
docs = ["sphinx"]

[tool.uv]
tool.uv.dev-dependencies = [".[tests,docs]", "ipython"]
```

This is not stuff you want (always) in your tox environments.

Extras for dev environments are totally coming, but until then, you should pass `--no-dev`.
